imports:
  - { resource: ../common.yml }

services:
  _defaults:
    public: true

  # Controller
  Oksydan\IsProductSlider\Controller\ProductSliderController:
    public: true
    class: Oksydan\IsProductSlider\Controller\ProductSliderController
    arguments:
      - "@=service('prestashop.adapter.legacy.context').getLanguages(false)"

  # installer
  oksydan.is_productslider.product_slider_installer:
    class: 'Oksydan\IsProductSlider\Installer\ProductSliderInstaller'
    arguments:
      - '@doctrine.dbal.default_connection'
      - '@oksydan.is_productslider.installer.database_yml_parser'
      - "@=service('prestashop.adapter.legacy.context').getContext()"

  oksydan.is_productslider.installer.database_yml_parser:
    class: 'Oksydan\IsProductSlider\Installer\DatabaseYamlParser'
    arguments:
      - '@oksydan.is_productslider.installer.database_yml_parser_provider'

  oksydan.is_productslider.installer.database_yml_parser_provider:
    class: 'Oksydan\IsProductSlider\Installer\Provider\DatabaseYamlProvider'
    arguments:
      - '@oksydan.is_productslider.module'

  oksydan.is_productslider.installer.action_database_create_table:
    class: 'Oksydan\IsProductSlider\Installer\ActionDatabaseCrateTable'
    parent: 'oksydan.is_productslider.installer.abstract_action_database'
    public: true

  oksydan.is_productslider.installer.action_database_drop_table:
    class: 'Oksydan\IsProductSlider\Installer\ActionDatabaseDropTable'
    parent: 'oksydan.is_productslider.installer.abstract_action_database'
    public: true

  oksydan.is_productslider.installer.abstract_action_database:
    class: 'Oksydan\IsProductSlider\Installer\ActionDatabaseAbstract'
    abstract: true
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  #creation/edition form
  oksydan.is_productslider.form.identifiable_object.data_provider.product_slider_form_data_provider:
    class: 'Oksydan\IsProductSlider\Form\Provider\ProductSliderFormDataProvider'
    arguments:
      - '@oksydan.is_productslider.repository.product_slider'
      - '@prestashop.core.admin.lang.repository'
      - '@prestashop.adapter.shop.context'

  oksydan.is_productslider.form.identifiable_object.builder.product_slider_form_builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: 'prestashop.core.form.builder.form_builder_factory:create'
    arguments:
      - 'Oksydan\IsProductSlider\Form\ProductSliderType'
      - '@oksydan.is_productslider.form.identifiable_object.data_provider.product_slider_form_data_provider'

  oksydan.is_productslider.form.identifiable_object.data_handler.product_slider_form_data_handler:
    class: 'Oksydan\IsProductSlider\Form\DataHandler\ProductSliderFormDataHandler'
    arguments:
      - '@oksydan.is_productslider.repository.product_slider'
      - '@prestashop.core.admin.lang.repository'
      - '@doctrine.orm.default_entity_manager'
      - "@=service('prestashop.adapter.legacy.context').getLanguages()"

  oksydan.is_productslider.form.identifiable_object.handler.product_slider_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@oksydan.is_productslider.form.identifiable_object.data_handler.product_slider_form_data_handler'

  #grid services
  oksydan.is_productslider.grid.definition.factory.product_slider:
    class: 'Oksydan\IsProductSlider\Grid\Definition\Factory\ProductSliderGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true

  oksydan.is_productslider.grid.query.product_slider_query_builder:
    class: 'Oksydan\IsProductSlider\Grid\Query\ProductSliderQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.adapter.shop.context'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"

  oksydan.is_productslider.grid.product_slider_grid_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@oksydan.is_productslider.grid.definition.factory.product_slider'
      - '@oksydan.is_productslider.grid.data.factory.product_slider_decorator'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'


  oksydan.is_productslider.grid.data.factory.product_slider_data_factory:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@oksydan.is_productslider.grid.query.product_slider_query_builder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'is_productslider'


  oksydan.is_productslider.grid.data.factory.product_slider_decorator:
    class: 'Oksydan\IsProductSlider\Grid\Data\Factory\ProductSliderGridDataFactory'
    arguments:
      - '@oksydan.is_productslider.grid.data.factory.product_slider_data_factory'

  # config form
  oksydan.is_productslider.product_slider.configuration:
    class: 'Oksydan\IsProductSlider\Form\DataConfiguration\ProductSliderDataConfiguration'
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.adapter.shop.context'
      - '@prestashop.adapter.multistore_feature'

  oksydan.is_productslider.product_slider_configuration.form_provider:
    class: 'Oksydan\IsProductSlider\Form\Provider\ProductSliderConfigurationFormDataProvider'
    arguments:
      - '@oksydan.is_productslider.product_slider.configuration'

  oksydan.is_productslider.product_slider_configuration.form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@oksydan.is_productslider.product_slider_configuration.form_provider'
      - 'Oksydan\IsProductSlider\Form\ProductSliderConfigurationType'
      - 'ProductSliderConfigurationForm'

  oksydan.is_productslider.form.product_slider_type:
    class: 'Oksydan\IsProductSlider\Form\ProductSliderType'
    parent: 'form.type.translatable.aware'
    arguments:
      - '@=service("prestashop.adapter.multistore_feature").isUsed()'
      - "@prestashop.adapter.legacy.context"
      - "@oksydan.is_productslider.configuration.product_slider_configuration"
    public: true
    tags:
      - { name: form.type }

  oksydan.is_productslider.form.product_slider_configuration_type:
    class: 'Oksydan\IsProductSlider\Form\ProductSliderConfigurationType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  oksydan.is_productslider.grid.position_definition:
    class: PrestaShop\PrestaShop\Core\Grid\Position\PositionDefinition
    arguments:
      - 'product_slider'
      - 'id_product_slider'
      - 'position'
